dist: xenial  # required for Python >= 3.7
language: python
python:
  - 3.7

cache:
  pip: true
  directories:
    - $HOME/.cache/pypoetry

install:
  - pip install --upgrade pip
  - pip install poetry
  - poetry install

script:
  - poetry run pytest tests/

deploy:
  provider: pypi
  server: https://test.pypi.org/legacy/
  user: $PYPI_USERNAME
  password: $PYPI_PASSWORD
  on:
    tags: true

branches:
  only:
    - master
