dist: xenial  # required for Python >= 3.7
language: python
python:
  - 3.7

cache:
  pip: true
  directories:
    - $HOME/.cache/pypoetry

install:
  - pip install --upgrade pip
  - pip install poetry
  - poetry install

script:
  - poetry run pytest tests/

before_deploy:
  - poetry config repositories.testpypi https://test.pypi.org/legacy/
  - poetry config http-basic.testpypi "$PYPI_USERNAME" "$PYPI_PASSWORD"

deploy:
  provider: script
  script:
    - poetry publish --repository=testpypi --build
  on:
    tags: true

branches:
  only:
    - master
    - /^v\d+\.\d+.\d+([a-z]+\d+)?/
